import React, { useContext } from 'react'
import Link from 'next/link'
import { motion, AnimatePresence } from 'framer-motion'
import Head from 'next/head'
import Navbar from './nav/Navbar'
import Notification from "../Notification"
// cookie consent
import CookieConsent from "react-cookie-consent"

// context import
import { MainContext } from '../../contexts/MainContext'
import Pricing from '../Pricing'

const Layout = ({ children }) => {

  // context
  const { showNotification, showPricing } = useContext(MainContext)
  
  return (
    <div>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CookieConsent
        location="bottom"
        contentStyle={{ flex: "unset" }}
        buttonClasses='rounded-lg font-bold'
        buttonText="Got it..."
        cookieName="RecipeApp"
        style={{ background: "#2B373B", marginBottom: "25px", width: "50%", left: "25%" }}
        buttonStyle={{ backgroundColor: "#8b5cf6", color: "#fff", fontSize: "13px" }}
        expires={5}
      >
        <div className='flex flex-col md:flex-row text-xs md:text-sm'>
          <p className='break-words'>
              This website uses cookies to enhance users experience.
          </p>
          <Link 
          href="/privacyPolicies"
          className='md:ml-3 underline'>
            Learn more
          </Link>
        </div>
      </CookieConsent>
      <AnimatePresence>
        {
          showNotification && 
          <motion.div 
          initial={{opacity: 0}}
          animate={{opacity: 1, y: 50}}
          transition={{duration: 0.5}}
          exit={{opacity: 0, y: -50}}
          className='fixed md:mr-5 z-40 top-0 right-0 flex justify-center pt-14 sm:w-2/3 md:w-96 lg:w-1/3'
          >
              <Notification />
          </motion.div>
        }
      </AnimatePresence>
      <AnimatePresence>
        {
          showPricing && (
            <motion.div
            initial={{opacity: 0}}
            animate={{opacity: 1, y: 0}}
            transition={{duration: 0.5}}
            exit={{opacity: 0, y: -50}}
            className='fixed md:mr-5 z-30 left-[12.5%] sm:left-[16.5%] md:left-1/3
            flex justify-center sm:w-2/3 md:w-96 lg:w-1/3 p-3 
            md:backdrop-filter md:backdrop-blur-sm rounded-md shadow-xl'
            >
              <Pricing />
            </motion.div>
          )
        }
      </AnimatePresence>
      <Navbar />
      {children}
    </div>
  )
}

export default Layout

