import React from 'react'
import { getCsrfToken } from "next-auth/react"
import Head from 'next/head'
import { useRouter } from "next/router"
import ResetPassword from '../../../components/auth/ResetPassword'

const ResetPasswordPage = ({ csrfToken }) => {

    const router = useRouter()

    const { resetpasswordtoken } = router.query

    return (
        <div>
            <Head>
                <title>Reset Password</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='h-screen relative'>
                <ResetPassword resetpasswordtoken={resetpasswordtoken} csrfToken={csrfToken} />
            </div>
        </div>
    )
}

export default ResetPasswordPage

// This is the recommended way for Next.js 9.3 or newer
export async function getServerSideProps(context) {
    return {
      props: {
        csrfToken: await getCsrfToken(context),
      },
    }
  }
